#author Christopher Millar 
import string 

numberL = []

#ciphertext to be deencrypted 
cWord = list("OBLIRSWCOVPXYBLIYDROBCWBMVKBODROOVNOBGRYCOPSBCDGSPORKNNSONKXNVOPDRSWKNKEQRDOBWKBBSONKCOMYXNVKDOSXVSPODRSCVKNIRKNCYWOGRKDEXOHZOMDONVILBYEQRDRSWDRBOOCYXCCYDRKDLODGOOXKXQOVDROIYEXQOCDKXNRSCPKDROBDROFSMKBDROBOCOOWONDYLOKVWYCDKWSCCSXQQOXOBKDSYXYPDROCOLYICDROKPYBOCKSNKXQOVDROMRSVNYPRSCYVNKQOGKCDROYXVICYXGRYRKNXYDDKUOXKEXSFOBCSDINOQBOODRYEQRROGKCDROCSXQVOYXOYPDROWGRYCOOKBVIZBYWSCOWSQRDRKFONYXOPEVVTECDSMODYKXKMKNOWSMKVDBKSXSXQCYWODGYYBDRBOOIOKBCLOPYBOKXQOVCKZZOKBKXMOKDDROWKBVYDDNKXMOYXKNKIGROXRORKNVOPDCMRYYVKXNGKCZEBCESXQRSCCDENSOCKDRYWOKZKBMOVMKWODYDROFSMKBKQOPBYWDROVYMKVLYYUCOVVOBCNSBOMDONDYDROBOFOBOXNTKWOCMVKBODROFSMKBRKFSXQYZOXONSDKXNPYEXNSDDYMYXDKSXKLYYUBOKNKPOGZKQOCGROBOEZYXROTEWZONEZPBYWRSCCOKDKXNGOXDCDBKSQRDDYDROCRYZGSDRDROLYYUEXNOBRSCKBWGRIRKCDRSCLOOXCOXDDYWIRYECOROKCUONZOBOWZDYBSVIRYVNSXQEZDROFYVEWOSDGKCYBNOBONCSBXYDLIWOYBKXIY") 

#give numerical value to each letter (0-25) put in numberL list 
for i in cWord:
	le = string.uppercase.index(i)
	numberL.append(le)
	
#decrypt and print out for each value of the shift 
num = 1
while(num<27):
	plainNL=[]
	complete = []
	for i in numberL:
		x = i - num 
		x = x%26 
		plainNL.append(x)
		
	for i in plainNL:
		le = string.uppercase[i]
		complete.append(le)
		
	print (''.join(complete))
	print "\n"
	num = num + 1