#author Christopher Millar 

import string 
import collections

#ciphertext to be deencrypted 
cWord = list("HRYPOABIWEALEEDTTCTEMNROREHUREAUHEBSKHEKSNUTEHLRDTAHDANORHREIONEUBSIAWOLNIEEORBSUAHHHLLGLNTYHPNHCOSIRDKCGELHNMENOTPSGIROSNTIAABFHHNOEDVATTFIVAHSUWTOALLAFORKBNSYONEIYUOMAAOITKENNHNLRRIBHATWODPROMEDUSDNETRTIASECGSODAYEDHIENVEWFEOSNMONTRFTFANAGNNDWLEHLRIRTOTHIEEAEOTEHFHNUBFOUSYETOGDROSEWNHDTGSGKYRAIETHLIETHTPBEDEHLHHORIYKSNEIODETVTXNTSFETYUTTEAMTUDNNOCEINHERSEDMANDSHSGRMOHNTPROTHFOSRAOERNOESEODFIGWTEMOEUETTNAATHNOLEDNNOHOHSSDNNRNTKEIHTPRAMPETFRNRFSOOWAGEGOTHHETESCMTEFSRWEEOLRASEDEERDGCAOEWNUPNHEWPEHTGNIEIYOMGYRSWEEGAASNEREHRSTNAETEPTFROIGTEWMOOTOTETWSSETDOVROTTRAODROLNTCHDGNEEPUOCHOGUEROHTITDEWOINNEETESIPNOROTOLHKMIIFRERHETAHATHEORTCWAMRSEHSACNAFBSHRSMWAGTRTEMALDELATPDNNMEAOUBIVVONRIOREAAWFHTSNLHROESKNTHAAIRUHRITENTSEHOHETOHTOSPBSKTSOHEIADRRARWOETTGFAUEENLTUETTTIRREATNRTTOOHUOEUENTOLRIAMTWEKWSADSOOHSAISOESTOORLOSTEIEELAAELMESABRERS") 	

length = len(cWord)

rangeList = []
for i in range(2,11):
	j = length / i 
	rangeList.append(j)

#decrpyt ciphertext column length 2-10
#to be selected one with english words  
for k in rangeList:
	list1=[]	
	a=0
	i=0
	while(i<k):
		a=i
		while(a<length):
			list1.append(cWord[a])
			a = a + k
		i = i + 1	
	print (''.join(list1))
	print "\n"